import { Judson } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/navbar";
import { cn } from "@/lib/utils";

const judson = Judson({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(judson.className, "pointer-events-none relative")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
